"""
Django settings for appointments project.

Generated by 'django-admin startproject' using Django 4.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""
import os
from pathlib import Path

from django.conf import locale
from django.utils.translation import gettext_lazy as _
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', "django-insecure-(%st!9pc%2d%*b3xt8@0o7*4rkxq-$6j3y-(b*ftz^m2^r4l$z")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True').lower() == 'true'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '*').split(',')

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "appointment.apps.AppointmentConfig",
]

# if you want to use Django Q for sending emails asynchronously, you must install django-q2 in your env
if os.environ.get('USE_DJANGO_Q', 'False').lower() == 'true':
    INSTALLED_APPS.append('django_q')

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",  # Pour servir les fichiers statiques en production
    "django.contrib.sessions.middleware.SessionMiddleware",
    'django.middleware.locale.LocaleMiddleware',
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "appointments.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'appointment/templates'],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "appointments.wsgi.application"

# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

# Configuration de la base de données
# Utilise PostgreSQL en production si DATABASE_URL est défini, sinon SQLite pour le développement
# Pendant le build (collectstatic), on utilise SQLite pour éviter les erreurs de connexion
DATABASE_URL = os.getenv('DATABASE_URL')
SKIP_DB = os.getenv('SKIP_DB_CONNECTION')

# En production (Render), forcer PostgreSQL si DATABASE_URL est défini
# IMPORTANT: Ne jamais utiliser SQLite en production si DATABASE_URL est défini
if DATABASE_URL and not SKIP_DB:
    try:
        import dj_database_url
        # Vérifier que psycopg (psycopg 3) ou psycopg2 est disponible avant d'utiliser PostgreSQL
        try:
            # Essayer d'importer psycopg 3 (moderne, supporte Python 3.13)
            try:
                import psycopg
                psycopg_available = True
            except ImportError:
                psycopg_available = False
                # Essayer d'importer psycopg2 de différentes façons
                try:
                    import psycopg2
                except ImportError:
                    try:
                        import psycopg2_binary as psycopg2
                    except ImportError:
                        raise ImportError("Neither psycopg (psycopg 3), psycopg2 nor psycopg2_binary can be imported")
            
            # Si psycopg (psycopg 3) ou psycopg2 est disponible, utiliser PostgreSQL
            db_config = dj_database_url.config(
                default=DATABASE_URL,
                conn_max_age=600,
                conn_health_checks=True,
            )
            # Forcer l'engine PostgreSQL (Django 5.2 supporte psycopg 3 et psycopg2)
            db_config['ENGINE'] = 'django.db.backends.postgresql'
            DATABASES = {
                'default': db_config
            }
            # Vérifier que c'est bien PostgreSQL
            engine = DATABASES['default'].get('ENGINE', '')
            import sys
            if psycopg_available:
                print(f"✅ Configuration PostgreSQL avec psycopg 3 (compatible Python 3.13): {engine}", file=sys.stderr)
            else:
                print(f"✅ Configuration PostgreSQL avec psycopg2: {engine}", file=sys.stderr)
            print(f"✅ Base de données: {DATABASES['default'].get('NAME')}", file=sys.stderr)
        except ImportError as e:
            # Si psycopg2 n'est pas disponible, vérifier pourquoi
            import sys
            import traceback
            print(f"❌ ERREUR CRITIQUE: psycopg2 non disponible", file=sys.stderr)
            print(f"❌ Exception: {e}", file=sys.stderr)
            print(f"❌ Traceback:", file=sys.stderr)
            traceback.print_exc(file=sys.stderr)
            print(f"❌ DATABASE_URL est défini mais psycopg2 n'est pas importable!", file=sys.stderr)
            # En production, on ne doit PAS utiliser SQLite si DATABASE_URL est défini
            raise ImportError(f"psycopg2 is required when DATABASE_URL is set: {e}")
    except ImportError as e:
        # Fallback si dj_database_url n'est pas installé
        import sys
        print(f"❌ ERREUR: dj_database_url non disponible: {e}", file=sys.stderr)
        raise ImportError("dj-database-url is required when DATABASE_URL is set")
    except Exception as e:
        # Si erreur de connexion, c'est une erreur en production
        import sys
        print(f"❌ ERREUR de configuration DB: {e}", file=sys.stderr)
        print(f"❌ DATABASE_URL: {DATABASE_URL[:50] if DATABASE_URL else 'None'}...", file=sys.stderr)
        # Ne pas utiliser SQLite en production si DATABASE_URL est défini
        raise Exception(f"Database configuration error: {e}")
else:
    if not DATABASE_URL:
        import sys
        print("ℹ️  DATABASE_URL non défini, utilisation de SQLite (développement)", file=sys.stderr)
    if SKIP_DB:
        import sys
        print("ℹ️  SKIP_DB_CONNECTION activé, utilisation de SQLite (build)", file=sys.stderr)
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "en"

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = "/static/"
STATICFILES_DIRS = [os.path.join(BASE_DIR, "appointment/static")]
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

# Configuration WhiteNoise pour servir les fichiers statiques en production
# Utilise CompressedStaticFilesStorage (plus simple et plus fiable que Manifest)
STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

APPOINTMENT_BUFFER_TIME = 0
APPOINTMENT_WEBSITE_NAME = 'Maw3idi'

# Payment Configuration
APPOINTMENT_PAYMENT_URL = 'appointment:select_payment_method'

# Banques et comptes bancaires en Mauritanie
BANK_ACCOUNTS = {
    'BAMIS': {
        'name': 'Banque Arabe Africaine en Mauritanie (BAMIS)',
        'account_number': os.getenv('BANK_BAMIS_ACCOUNT', '000000000000'),
        'iban': os.getenv('BANK_BAMIS_IBAN', ''),
        'swift': os.getenv('BANK_BAMIS_SWIFT', ''),
    },
    'BPM': {
        'name': 'Banque Populaire de Mauritanie (BPM)',
        'account_number': os.getenv('BANK_BPM_ACCOUNT', '000000000000'),
        'iban': os.getenv('BANK_BPM_IBAN', ''),
        'swift': os.getenv('BANK_BPM_SWIFT', ''),
    },
    'CHINGUITEL_CASH': {
        'name': 'Chinguitel Cash',
        'account_number': os.getenv('CHINGUITEL_CASH_NUMBER', ''),
    },
}

# Configuration des cartes bancaires (pour intégration future avec Stripe ou autre)
PAYMENT_CARD_ENABLED = os.getenv('PAYMENT_CARD_ENABLED', 'True').lower() == 'true'
STRIPE_PUBLIC_KEY = os.getenv('STRIPE_PUBLIC_KEY', '')
STRIPE_SECRET_KEY = os.getenv('STRIPE_SECRET_KEY', '')
STRIPE_WEBHOOK_SECRET = os.getenv('STRIPE_WEBHOOK_SECRET', '')

# Social Media URLs - Configurez vos URLs de réseaux sociaux ici
SOCIAL_MEDIA_FACEBOOK_URL = os.getenv('SOCIAL_MEDIA_FACEBOOK_URL', 'https://www.facebook.com/')
SOCIAL_MEDIA_INSTAGRAM_URL = os.getenv('SOCIAL_MEDIA_INSTAGRAM_URL', 'https://www.instagram.com/')
SOCIAL_MEDIA_LINKEDIN_URL = os.getenv('SOCIAL_MEDIA_LINKEDIN_URL', 'https://www.linkedin.com/')

LANGUAGES = (
    ('en', _('English')),
    ('fr', _('French')),
    # ('es', _('Spanish')), # uncomment to add Spanish
)

# Email Configuration
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.example.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')

# Check
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True').lower() == 'true'
EMAIL_USE_SSL = os.getenv('EMAIL_USE_SSL', 'False').lower() == 'true'

# If SSL is True, TLS will be set to False
# Can't have both SSL and TLS set to True :(
if EMAIL_USE_SSL:
    EMAIL_USE_TLS = False
    # Default SSL port if not specified is 465
    EMAIL_PORT = int(os.getenv('EMAIL_PORT', 465))

EMAIL_SUBJECT_PREFIX = os.getenv('EMAIL_SUBJECT_PREFIX', '')
EMAIL_USE_LOCALTIME = os.getenv('EMAIL_USE_LOCALTIME', 'True').lower() == 'true'
SERVER_EMAIL = os.getenv('SERVER_EMAIL', EMAIL_HOST_USER)
USE_DJANGO_Q_FOR_EMAILS = os.getenv('USE_DJANGO_Q_FOR_EMAILS', 'True').lower() == 'true'
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER)

# Little warning if EMAIL_HOST_USER or EMAIL_HOST_PASSWORD is not set
# This won't appear in the console when using the package, only when running the Django project or docker-compose
if not EMAIL_HOST_USER or not EMAIL_HOST_PASSWORD:
    print("Warning: EMAIL_HOST_USER or EMAIL_HOST_PASSWORD is not set. Email functionality may be limited.")

# Warn if both TLS and SSL are set to True (only appears when running the Django project or docker-compose)
# To be honest, this would be unique if you do this in your .env, I mean, come on :(
if EMAIL_USE_TLS and EMAIL_USE_SSL:
    print("Warning: Both EMAIL_USE_TLS and EMAIL_USE_SSL are set to True. Only SSL will be used.")

# ADMINS configuration
ADMIN_NAME = os.getenv('ADMIN_NAME', 'Admin')
ADMIN_EMAIL = os.getenv('ADMIN_EMAIL', '')
ADMINS = [(ADMIN_NAME, ADMIN_EMAIL)] if ADMIN_EMAIL else []

# Same as above, only appears when running the Django project or docker-compose
if not ADMIN_EMAIL:
    print("Warning: ADMIN_EMAIL is not set. Error emails will not be sent to administrators.")

# if using Django Q, example of extra configuration (you can change this to your liking)
if 'django_q' in INSTALLED_APPS:
    Q_CLUSTER = {
        'name': 'django-appointment',
        'workers': 4,
        'timeout': 90,
        'retry': 180,  # retry must be larger than timeout (increased to avoid warning)
        'queue_limit': 50,
        'bulk': 10,
        'orm': 'default',
        # Redis configuration (optional, comment out if not using Redis)
        # 'redis': {
        #     'host': 'redis',
        #     'port': 6379,
        #     'db': 0,
        # }
    }
